const legos=[
 {
  "Id": 1,
  "Nombre": "Notre-Dame de Paris",
  "Precio": 349.99,
  "Categoria": "Architeture",
  "Estado": ["Hard to Find"],
  "Altura": "33cm",
  "Ancho": "22cm",
  "Profundidad": "41cm",
  "Modelo": 21061,
  "Piezas": 4383,
  "Edad minima": 18,
  "Anio Lanzamiento": 2018,
  "Descripcion": "Experience every stage in the development of an iconic Paris landmark with the collectible LEGO® Architecture Notre-Dame de Paris building set for adults (21061). This architectural model kit takes you on a historic building journey beginning in 1163, when the first stone was laid, through architect Viollet-le-Duc’s redesign work in the 19th century to Notre-Dame’s majestic appearance before the fire of 2019.",
  "Calificacion": "4.8",
  "Cantidad": 15,
  "Img": ["https://www.lego.com/cdn/cs/set/assets/bltfc5b67804768a899/21061_alt1.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", 
          "https://www.lego.com/cdn/cs/set/assets/blt25974a0c97248d6b/21061_Box5_v39.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 2,
  "Nombre": "Great Piramid of Giza",
  "Precio": 229.99,
  "Categoria": "Architeture",
  "Estado": ["Hard to Find"],
  "Altura": "20cm",
  "Ancho": "35cm",
  "Profundidad": "32cm",
  "Modelo": 21058,
  "Piezas": 1476,
  "Edad minima": 18,
  "Anio Lanzamiento": 2017,
  "Descripcion": "Take an imaginative leap back in time to the 26th century BC and experience the building of one of the Seven Wonders of the Ancient World with this LEGO® Architecture Great Pyramid of Giza model (21058). Build a beautifully detailed cross-section model of the Great Pyramid, revealing its main tunnels and chambers and the system that may have been used to move huge stones during its construction. Visualise how this area by the River Nile is thought to have looked in ancient times, with 2 small pyramids, 2 mortuary temples, Sphinx statues, an obelisk and more.",
  "Calificacion": "4.5",
  "Cantidad": 15,
  "Img": ["https:\/\/www.lobigo.de\/media\/c2\/bf\/fb\/1655370492\/Nr-26357_4.jpg.pagespeed.ce.U7tSEJPDqA.jpg", "https:\/\/th.bing.com\/th\/id\/R.fbc6df5e76360117db8d7ef151b27e07?rik=ySr1z2TgJE53FA&riu=http%3a%2f%2fwww.brickfinder.net%2fwp-content%2fuploads%2f2022%2f05%2fLEGO-Architecture-Pyramids-of-Giza-21058-05-768x587.jpg&ehk=R7Ce9qK%2bAzUZrVNhA%2bMJSGXAn%2fg2HQKniJB%2braEOmEY%3d&risl=&pid=ImgRaw&r=0"]
 },
 {
  "Id": 3,
  "Nombre": "Lego House",
  "Precio": 79.99,
  "Categoria": "Architeture",
  "Estado": ["Exclusive", "Best Seller", "Hard to Find"],
  "Altura": "6cm",
  "Ancho": "22cm",
  "Profundidad": "19cm",
  "Modelo": 21037,
  "Piezas": 774,
  "Edad minima": 12,
  "Anio Lanzamiento": 2021,
  "Descripcion": "Experience the magic of the world’s only LEGO® House with this amazing, brightly colored LEGO Architecture model, featuring 21 unique interlocking, brick-shaped rooms, transparent facade elements, multicolored roof, roof terraces and giant outdoor stairways. Remove the brick-shaped keystone roof section to access the interior public square, complete with a staircase and the LEGO Tree of Creativity. This highly detailed LEGO model has been designed to deliver a pleasant and rewarding building experience for all with an interest in architecture, travel, history and design, and makes a perfect display piece for the home or office.",
  "Calificacion": "4.5",
  "Cantidad": 7,
  "Img": ["https:\/\/media.cnn.com\/api\/v1\/images\/stellar\/prod\/190821121332-lego-test-3.jpg?q=w_1110,c_fill", "https:\/\/jaysbrickblog.com\/wp-content\/uploads\/2023\/10\/21037_alt3-1400x1050.jpg"]
 },
 {
  "Id": 4,
  "Nombre": "Paris",
  "Precio": 79.99,
  "Categoria": "Architeture",
  "Estado": ["Hard to Find"],
  "Altura": "22cm",
  "Ancho": "28cm",
  "Profundidad": "11cm",
  "Modelo": 21044,
  "Piezas": 649,
  "Edad minima": 12,
  "Anio Lanzamiento": 2019,
  "Descripcion": "Bring together iconic Paris landmarks with this magnificent Paris skyline model. The 21044 LEGO® Architecture Skyline Collection set features the Arc de Triomphe, Champs-Elysées, Tour Montparnasse, Grand Palais, Eiffel Tower and the Louvre, and is finished with grass and tree areas and a decorative Paris nameplate. This set has been designed to deliver a rewarding and relaxing building experience to all with an interest in architecture, travel, history and design, and makes a truly “magnifique” centerpiece for the home or office. Each skyline model is scaled to give an accurate representation of the comparative size of the featured structures, with realistic color depiction.",
  "Calificacion": "4.5",
  "Cantidad": 5,
  "Img": ["https:\/\/sh-s7-live-s.legocdn.com\/is\/image\/LEGO\/21044?scl=1.7&op_sharpen=1", "https:\/\/buildandplay.com.au\/wp-content\/uploads\/21044-3.png"]
 },
 {
  "Id": 5,
  "Nombre": "Statue of Liberty",
  "Precio": 149.99,
  "Categoria": "Architeture",
  "Estado": ["Hard to Find"],
  "Altura": "44cm",
  "Ancho": "14cm",
  "Profundidad": "14cm",
  "Modelo": 21042,
  "Piezas": 1685,
  "Edad minima": 16,
  "Anio Lanzamiento": 2023,
  "Descripcion": "Celebrate a monumental blend of architecture and sculpture with this LEGO® Architecture 21042 The Statue of Liberty set. America’s iconic symbol of freedom stands more than 305 feet above Liberty Island in New York harbor, welcoming seafarers from around the globe. This impressive LEGO interpretation faithfully reproduces the monument's harmonious blend of sculpture and architecture with its intricately detailed shield-lined pedestal, brick detailing and columned balconies. The beautifully crafted Lady Liberty statue features a flowing robe, broken shackles, 7-ray crown, iconic tablet and an upraised arm bearing a golden torch. Finished with an authentic sand-green and beige color scheme, and a decorative nameplate, this model delivers a highly satisfying building experience to all with an interest in architecture, travel, history and design, and makes a truly symbolic centerpiece for the home or office.",
  "Calificacion": "4.6",
  "Cantidad": 20,
  "Img": ["https:\/\/th.bing.com\/th\/id\/OIP.ncuFaodorWiplkY23mhRAwAAAA?rs=1&pid=ImgDetMain", "https:\/\/www.sam-turner.co.uk\/cdn\/shop\/products\/21042_alt4_1024x1024@2x.jpg?v=1634913579"]
 },
 {
  "Id": 6,
  "Nombre": "Taj Mahal",
  "Precio": 179.99,
  "Categoria": "Architeture",
  "Estado": ["Hard to Find"],
  "Altura": "20cm",
  "Ancho": "23cm",
  "Profundidad": "23cm",
  "Modelo": 21056,
  "Piezas": 2022,
  "Edad minima": 18,
  "Anio Lanzamiento": 2022,
  "Descripcion": "This inspiring, hands-on challenge to enjoy in your spare time lets you recreate a symbol of eternal love and an architectural wonder of the world in LEGO style. Revel in authentic details such as the crypt with tombs of Mumtaz and Shah Jahan, central chamber with 2 cenotaphs, monumental iwans, main dome, 4 chhatris and 4 slender minarets. A LEGO brick inscribed ‘Taj Mahal’ completes a scale model that is sure to wow people wherever it is displayed.",
  "Calificacion": "4.7",
  "Cantidad": 15,
  "Img": ["https:\/\/th.bing.com\/th\/id\/OIP.c64OgJXj93cAnEqyQXZKLAHaHa?w=800&h=800&rs=1&pid=ImgDetMain", "https:\/\/www.toysrus.ca\/dw\/image\/v2\/BDFX_PRD\/on\/demandware.static\/-\/Sites-toys-master-catalog\/default\/dwd767f2d8\/images\/A40E4965_4.jpg?sw=767&sh=767&sm=fit"]
 },
 {
  "Id": 7,
  "Nombre": "NASA Artemis Space Lunch",
  "Precio": 449.99,
  "Categoria": "Architeture",
  "Estado": ["Exclusive", "Last Chance"],
  "Altura": "70cm",
  "Ancho": "27cm",
  "Profundidad": "30cm",
  "Modelo": 10341,
  "Piezas": 3601,
  "Edad minima": 18,
  "Anio Lanzamiento": 2021,
  "Descripcion": "This accurate replica depicts real launch systems and includes retractable launch tower umbilicals, rocket support and crew bridge, detachable solid-fuel boosters and separating rocket stages. The set also includes a model of the Orion module with foldout solar panels, which can be placed inside the rocket or on a separate display stand. A printed plaque adds the finishing touch to this impressive model, perfect for home and office decor.",
  "Calificacion": "4.6",
  "Cantidad": 3,
  "Img": ["https:\/\/preview.redd.it\/the-scale-is-not-identical-to-the-saturn-v-set-but-i-have-a-v0-rb51k5v8bowc1.jpeg?width=1080&crop=smart&auto=webp&s=6ed3581eb9799b9b8deaeb97ee6f6c380bd6a41a", "https:\/\/mlpnk72yciwc.i.optimole.com\/cqhiHLc.IIZS~2ef73\/w:auto\/h:auto\/q:75\/https:\/\/bleedingcool.com\/wp-content\/uploads\/2024\/04\/10341_alt3.jpeg"]
 },
 {
  "Id": 8,
  "Nombre": "Eiffel Tower",
  "Precio": 999.99,
  "Categoria": "Architeture",
  "Estado": ["Exclusive", "Last Chance"],
  "Altura": "149cm",
  "Ancho": "57cm",
  "Profundidad": "57cm",
  "Modelo": 10307,
  "Piezas": 10001,
  "Edad minima": 18,
  "Anio Lanzamiento": 2015,
  "Descripcion": "Just like the original construction in Paris, France, this collectible model is assembled in 4 sections. The process closely follows the way the real tower was built, giving you a unique insight into Gustave Eiffel’s engineering brilliance. Discover true-to-life details throughout, including landscaping, 3 observation platforms, lifts and a broadcast tower, topped off with the French flag.",
  "Calificacion": "4.3",
  "Cantidad": 2,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt95b2930fbcf9ea6b\/10307_alt1.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt1c61dd3796a7b8a7\/10307_alt11.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 9,
  "Nombre": "Titanic",
  "Precio": 999.99,
  "Categoria": "Architeture",
  "Estado": ["Exclusive", "Last Chance"],
  "Altura": "44cm",
  "Ancho": "16cm",
  "Profundidad": "135cm",
  "Modelo": 10294,
  "Piezas": 9090,
  "Edad minima": 18,
  "Anio Lanzamiento": 2020,
  "Descripcion": "This 1:200 scale model is designed in 3 sections, faithfully recreating the features of the Titanic. The cross section reveals interior details like the first-class dining room, the grand staircases, one of the boiler rooms and many cabins from the different passenger classes. Bring the story of the Titanic to life by recreating details such as the ship’s bridge, promenade deck, reading lounge, swimming pool and many more. This magnificent model makes a perfect gift for history buffs.",
  "Calificacion": "4.8",
  "Cantidad": 1,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/bltb94632aeb971eb91\/10294.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt4970f39471f38330\/10294_alt1.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 10,
  "Nombre": "Colosseum",
  "Precio": 950.99,
  "Categoria": "Architeture",
  "Estado": ["Exclusive", "Best Seller"],
  "Altura": "27cm",
  "Ancho": "52cm",
  "Profundidad": "59cm",
  "Modelo": 10276,
  "Piezas": 9036,
  "Edad minima": 18,
  "Anio Lanzamiento": 2020,
  "Descripcion": "Nowhere on Earth compares to the majesty of the Colosseum of Rome. So, get ready to escape your everyday life as you take on the biggest ever LEGO® build (as at November 2020) yet. This epic 9,036-piece Colosseum model depicts each part of the famous structure in great detail. Authentic detailing shows the northern part of the outer wall’s facade and its iconic arches. The model features 3 storeys, adorned with columns of the Doric, Ionic and Corinthian orders while the attic is decorated with Corinthian pilasters.",
  "Calificacion": "4.5",
  "Cantidad": 7,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt26cc4dd7f5cf656e\/10276_alt1.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt256d4b7677c4bc86\/10276_alt14.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 11,
  "Nombre": "Arc de Triomphe",
  "Precio": 325.99,
  "Categoria": "Architeture",
  "Estado": ["Best Seller"],
  "Altura": "11cm",
  "Ancho": "14cm",
  "Profundidad": "9cm",
  "Modelo": 21036,
  "Piezas": 386,
  "Edad minima": 12,
  "Anio Lanzamiento": 2022,
  "Descripcion": "Capture the architectural elegance of one of the world’s best-known monuments with this impressive LEGO® Architecture interpretation of the Arc de Triomphe. This detailed model faithfully reproduces Paris’ iconic masterpiece, with statue-adorned pillars, sculptural reliefs and subtle coloring that adds warmth while emphasizing the model’s bold lines, curves and contours. It also includes a golden plate to represent the Tomb of the Unknown Soldier, a LEGO interpretation of the eternal flame and a decorative “Arc de Triomphe” nameplate. This LEGO brick model has been designed to deliver a pleasantly challenging and rewarding building experience for all with an interest in architecture, travel, history and design, and makes a perfect display piece for the home or office.",
  "Calificacion": "4.5",
  "Cantidad": 4,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt353cb3680dcf82a0\/21036.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt959d5b6f281400b9\/21036_alt6.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 12,
  "Nombre": "Tokyo",
  "Precio": 79.99,
  "Categoria": "Architeture",
  "Estado": ["New", "Best Seller"],
  "Altura": "28cm",
  "Ancho": "27cm",
  "Profundidad": "10cm",
  "Modelo": 21051,
  "Piezas": 547,
  "Edad minima": 16,
  "Anio Lanzamiento": 2023,
  "Descripcion": "Recreate some of Tokyo’s most famous buildings with this detailed LEGO® Architecture Skyline Collection 21051 desk toy. It’s a great souvenir for Tokyo visitors and an ideal gift for adults who live or have lived in Japan’s capital city or who dream of visiting. Even LEGO newcomers can zone out from busy lives and enjoy this relaxing building experience.Iconic buildingsThis toy construction set includes scale models of TOKYO SKYTREE, the world’s tallest freestanding tower, Tokyo Tower, Mode Gakuen Cocoon Tower and Tokyo Big Sight. The cherry-tree-filled Chidorigafuchi Park, a classic pagoda tower and Shibuya Crossing are also featured. Together on the baseplate with a ‘Tokyo’ nameplate, they create a compact, impactful display piece.Introducing LEGO Architecture…LEGO Architecture sets capture the essence of the world’s best-known buildings, monuments and cities. From iconic landmarks to city skyline models, there’s something for anyone interested in architecture, travel, history and design.",
  "Calificacion": "4.6",
  "Cantidad": 7,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt0b2057b44f21d3bb\/21051.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt73e5da5fad2c19f4\/21051_alt4.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 13,
  "Nombre": "C-3PO",
  "Precio": 299.99,
  "Categoria": "Star Wars",
  "Estado": ["New", "Last Chance"],
  "Altura": "38cm",
  "Ancho": 0,
  "Profundidad": 0,
  "Modelo": 1035,
  "Piezas": 1138,
  "Edad minima": 18,
  "Anio Lanzamiento": 2024,
  "Descripcion": "Build and display this intricately detailed LEGO® Star Wars™ C-3PO buildable droid figure. A nostalgic gift idea for adults and any fans of the classic Star Wars saga, this collectible set offers an immersive and rewarding creative challenge. Recreate every detail of the beloved Star Wars character and turn his head or move his arms to create familiar poses.",
  "Calificacion": "4.7",
  "Cantidad": 3,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/bltc6618252c9d34a94\/75398_boxprod_v39_sha.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt8be5c66772fd89a5\/75398_WEB_SEC01_NOBG.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 14,
  "Nombre": "Imperial Star Destroyer",
  "Precio": 299.99,
  "Categoria": "Star Wars",
  "Estado": ["New", "Last Chance"],
  "Altura": "16cm",
  "Ancho": "46cm",
  "Profundidad": "29cm",
  "Modelo": 1350,
  "Piezas": 1555,
  "Edad minima": 10,
  "Anio Lanzamiento": 2023,
  "Descripcion": "Dominate the galaxy with this LEGO® Star Wars™ Imperial Star Destroyer buildable toy starship playset for kids (75394). A cool birthday gift for boys, girls and fans aged 10 and up, this Star Wars starship building toy features a hidden foldout carry handle for flying and 2 spring-loaded shooters, with a lift-off top panel and foldout side panels for easy access to the detailed interior. Playful details inside include the bridge, command room, break room, armory, control panels and cargo box with thermal detonator elements.",
  "Calificacion": "4.7",
  "Cantidad": 2,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/bltb6f5dfaf01195072\/75394_Prod.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/bltdb56c153a3d6810c\/75394_WEB_SEC03_NOBG.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 15,
  "Nombre": "TIE Interceptor",
  "Precio": 349.99,
  "Categoria": "Star Wars",
  "Estado": ["Exclusive", "Last Chance"],
  "Altura": "32cm",
  "Ancho": "40cm",
  "Profundidad": "33cm",
  "Modelo": 75382,
  "Piezas": 1931,
  "Edad minima": 18,
  "Anio Lanzamiento": 2021,
  "Descripcion": "Spark memories of classic Star Wars™ saga action with this LEGO® Star Wars Ultimate Collector Series buildable TIE Interceptor model (75382) for adults. The iconic TIE Interceptor starfighter was part of the first-ever launch of LEGO Star Wars UCS sets in the year 2000; now it’s back and redesigned for even greater authenticity. Revel in buildable details, such as its distinctive wings, cockpit interior, laser cannons and rear engine.",
  "Calificacion": "4.4",
  "Cantidad": 2,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt42c7adf188ed2eb8\/75382.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/bltd2c0cbf6b728ab6c\/75382_alt1.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 16,
  "Nombre": "Millenium Falcon",
  "Precio": 1299.99,
  "Categoria": "Star Wars",
  "Estado": ["Hard to Find"],
  "Altura": "21cm",
  "Ancho": "84cm",
  "Profundidad": "60cm",
  "Modelo": 75192,
  "Piezas": 7541,
  "Edad minima": 16,
  "Anio Lanzamiento": 2022,
  "Descripcion": "Welcome to the largest, most detailed LEGO® Star Wars Millennium Falcon model we’ve ever created—in fact, with 7,500 pieces it’s one of our biggest LEGO models, period! This amazing LEGO interpretation of Han Solo’s unforgettable Corellian freighter has all the details that Star Wars fans of any age could wish for, including intricate exterior detailing, upper and lower quad laser cannons, landing legs, lowering boarding ramp and a 4-minifigure cockpit with detachable canopy. Remove individual hull plates to reveal the highly detailed main hold, rear compartment and gunnery station. This amazing model also features interchangeable sensor dishes and crew, so you decide whether to play out classic LEGO Star Wars adventures with Han, Leia, Chewbacca and C-3PO, or enter the world of Episode VII and VIII with older Han, Rey, Finn and BB-8!",
  "Calificacion": "4.5",
  "Cantidad": 5,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blte22f1f8d1cacfb3c\/75192_alt1.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/bltecd03cc9fb82fd56\/75192_alt2.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 17,
  "Nombre": "X-Wing Starfighter",
  "Precio": 369.99,
  "Categoria": "Star Wars",
  "Estado": ["Exclusive", "Last Chance"],
  "Altura": "27cm",
  "Ancho": "44cm",
  "Profundidad": "55cm",
  "Modelo": 75355,
  "Piezas": 1953,
  "Edad minima": 18,
  "Anio Lanzamiento": 2018,
  "Descripcion": "Recall exciting scenes from the Star Wars™ trilogy and Star Wars: The Mandalorian as you build this stunningly detailed Ultimate Collector Series version of an X-Wing Starfighter (75355). Channel the focus of a Jedi to recreate authentic details using LEGO® bricks, including the opening cockpit, space behind the cockpit for the R2-D2 LEGO droid figure, and wings that can be adjusted from flight mode into attack mode at the turn of a switch.",
  "Calificacion": "3.3",
  "Cantidad": 3,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt3e07af4c83a87efd\/75355.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/bltf43b9114793d8769\/75355_alt8.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 18,
  "Nombre": "Darth Vader Helmet",
  "Precio": 119.99,
  "Categoria": "Star Wars",
  "Estado": ["Hard to Find"],
  "Altura": "20cm",
  "Ancho": "15cm",
  "Profundidad": "14cm",
  "Modelo": 75304,
  "Piezas": 834,
  "Edad minima": 18,
  "Anio Lanzamiento": 2018,
  "Descripcion": "The Darth Vader Helmet is a compact size and has a display stand with a nameplate to complete a striking centrepiece that will enhance the decor of your home or workplace. And check out the other new-for-May-2021 LEGO Star Wars build-to-display helmet: Scout Trooper Helmet (75305).",
  "Calificacion": "4.7",
  "Cantidad": 5,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt98788132422b6a0f\/75304_WEB_PRI_NOBG.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/bltd8d450bb21ed629e\/75304_alt14.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 19,
  "Nombre": "R2-D2",
  "Precio": 369.99,
  "Categoria": "Star Wars",
  "Estado": ["Last Chance"],
  "Altura": "31cm",
  "Ancho": "19cm",
  "Profundidad": "15cm",
  "Modelo": 75308,
  "Piezas": 2314,
  "Edad minima": 18,
  "Anio Lanzamiento": 2020,
  "Descripcion": "Relive classic Star Wars™ moments as you build this exceptionally detailed R2-D2 LEGO® droid figure. The brilliant new-for-May-2021 design is packed with authentic details, including a retractable mid-leg, rotating head, opening and extendable front hatches, a periscope that can be pulled up and turned, and Luke Skywalker’s lightsaber hidden in a compartment in the head.",
  "Calificacion": "4.5",
  "Cantidad": 3,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt8ca6852351b6c047\/75379.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt7c55f6ba54172ae4\/75379_alt6.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 20,
  "Nombre": "Mos Espa Podrace Diorama",
  "Precio": 119.99,
  "Categoria": "Star Wars",
  "Estado": ["Hard to Find"],
  "Altura": "12cm",
  "Ancho": "30cm",
  "Profundidad": "14cm",
  "Modelo": 75380,
  "Piezas": 718,
  "Edad minima": 18,
  "Anio Lanzamiento": 2022,
  "Descripcion": "Freeze-frame a moment from the thrilling Mos Espa Podrace with this LEGO® Star Wars™ Diorama (75380) buildable model kit for adults. This collectible building set invites you to channel the force, as Anakin Skywalker did in the Star Wars: The Phantom Menace adventure, to create a LEGO brick-built snapshot of his Podracer powering through Arch Canyon in hot pursuit of his racing rival Sebulba.",
  "Calificacion": "4.6",
  "Cantidad": 15,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/bltf844b7f02ed08d82\/75380.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt2a089db2d3ccc96e\/75380_Box5_v39.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 21,
  "Nombre": "Clone Commander Helmet",
  "Precio": 99.99,
  "Categoria": "Star Wars",
  "Estado": ["Hard to Find"],
  "Altura": "21cm",
  "Ancho": "12cm",
  "Profundidad": "14cm",
  "Modelo": 75350,
  "Piezas": 766,
  "Edad minima": 18,
  "Anio Lanzamiento": 2017,
  "Descripcion": "Pay homage to a loyal soldier with this collectible LEGO® Star Wars™ Clone Commander Cody Helmet (75350) build-and-display model for adults. Enjoy the mindful, satisfying process of recreating the distinctive contours of the helmet worn by this iconic character in Star Wars: The Clone Wars. A brick-built stand with a nameplate completes an eye-catching centrepiece.",
  "Calificacion": "4.3",
  "Cantidad": 15,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt047686711ed3cb43\/75350.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt75df9d867f5464ad\/75350_alt2.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 22,
  "Nombre": "Princess Leia Helmet",
  "Precio": 99.99,
  "Categoria": "Star Wars",
  "Estado": ["Last Chance", "New"],
  "Altura": "17cm",
  "Ancho": "11cm",
  "Profundidad": "14cm",
  "Modelo": 75351,
  "Piezas": 670,
  "Edad minima": 18,
  "Anio Lanzamiento": 2024,
  "Descripcion": "Pay homage to a legendary character with this LEGO® Star Wars™ Princess Leia (Boushh) Helmet (75351) build-and-display model for adults. Channel your creative Force to recreate the bounty hunter helmet worn by Princess Leia as a disguise to enter Jabba the Hutt’s palace in Star Wars: Return of the Jedi. A buildable stand with a nameplate completes an admirable centrepiece.",
  "Calificacion": "4.6",
  "Cantidad": 2,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt32953937b372413f\/75351.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blte44ef8c34ae21159\/75351_alt2.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 23,
  "Nombre": "AT-AT",
  "Precio": 1299.99,
  "Categoria": "Star Wars",
  "Estado": ["Hard to Find", "Best Seller"],
  "Altura": "62cm",
  "Ancho": "24cm",
  "Profundidad": "69cm",
  "Modelo": 75313,
  "Piezas": 6785,
  "Edad minima": 18,
  "Anio Lanzamiento": 2015,
  "Descripcion": "This is the AT-AT (75313) that every LEGO® Star Wars™ fan has been waiting for. This epic Ultimate Collector Series build-and-display model features posable legs and head, cannons with a realistic recoil action, rotating cannons, bomb-drop hatch and a hook to attach to Luke Skywalker’s line, just like in the Battle of Hoth.",
  "Calificacion": "4.2",
  "Cantidad": 7,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blta7b7b825b6d4fc0a\/75313_Prod.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt705c9c053273f516\/75313_Box5_v29.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 24,
  "Nombre": "The Mandalorian Helmet",
  "Precio": 99.99,
  "Categoria": "Star Wars",
  "Estado": ["Hard to Find"],
  "Altura": "18cm",
  "Ancho": "11cm",
  "Profundidad": "12cm",
  "Modelo": 75328,
  "Piezas": 584,
  "Edad minima": 18,
  "Anio Lanzamiento": 2016,
  "Descripcion": "Attention Star Wars: The Mandalorian fans: get into your creative zone and focus on building this collectible LEGO® Star Wars™ replica of The Mandalorian’s helmet (75328). The metallic sheen of beskar armour is cleverly recreated with drum-lacquered elements, while bricks in different shades of grey allow you to highlight the authentic replica’s contours. Add the brick-built display stand with nameplate to complete a striking centrepiece for your home or workplace.",
  "Calificacion": "4.7",
  "Cantidad": 15,
  "Img": ["https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blta6da339d766e9905\/75328.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5", "https:\/\/www.lego.com\/cdn\/cs\/set\/assets\/blt1335a995e621255a\/75328_alt2.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5"]
 },
 {
  "Id": 25,
  "Nombre": "Retro Radio",
  "Precio": 169.99,
  "Categoria": "Ideas",
  "Estado": ["Exclusive"],
  "Altura": "32cm",
  "Ancho": "23cm",
  "Profundidad": "7cm",
  "Modelo": 10334,
  "Piezas": 906,
  "Edad minima": 18,
  "Anio Lanzamiento": 2021,
  "Descripcion": "Enjoy an immersive building project with this LEGO® Icons Retro Radio (10334) set. Craft an ornamental replica of a 1970s vintage radio with a foldup handle and antenna, classic power and tuning dials and a sliding frequency switch. Rotate the dials to emit tuning signals and music snippets. Mount a smartphone in the rear compartment to relish your favourite tunes while bringing a cool retro vibe to your home or office.",
  "Calificacion": "4.7",
  "Cantidad": 3,
  "Img": ["https:\/\/www.thebrickfan.com\/wp-content\/uploads\/2024\/05\/LEGO-Icons-Retro-Radio-10334-6.jpg", "https:\/\/mlpnk72yciwc.i.optimole.com\/cqhiHLc.IIZS~2ef73\/w:auto\/h:auto\/q:75\/https:\/\/bleedingcool.com\/wp-content\/uploads\/2024\/05\/10334_Box5_v39.jpeg"]
 },
 {
  "Id": 26,
  "Nombre": "Chevrolet Camaro Z28",
  "Precio": 249.99,
  "Categoria": "Ideas",
  "Estado": ["Hard to Find", "New"],
  "Altura": "10cm",
  "Ancho": "14cm",
  "Profundidad": "36cm",
  "Modelo": 10304,
  "Piezas": 1456,
  "Edad minima": 18,
  "Anio Lanzamiento": 2023,
  "Descripcion": "Just like the classic 1969 Chevrolet Camaro Z28, this highly accurate collectible LEGO® model car comes with a host of options so you can personalise your car, your way. With the roof or convertible? Classic or hideaway front headlights? White, grey or red racing stripes? The choice is yours. But this car’s impressive looks are just the start. Authentic features include a detailed V8 engine, working steering and opening doors, plus opening bonnet and boot.",
  "Calificacion": "4.5",
  "Cantidad": 5,
  "Img": ["https:\/\/images.novelship.com\/product\/1677827917702_LEGO1969Ch1.octet-stream?fit=fill&bg=FFFFFF&trim=color&auto=format,compress&q=75&h=400", "https:\/\/s3-us-west-2.amazonaws.com\/media.brothers-brick.com\/2022\/07\/LEGO-Icons-10304-Chevrolet-Camaro-Z28-1-1024x740.jpg"]
 },
 {
  "Id": 27,
  "Nombre": "PAC-MAN Arcade",
  "Precio": 399.99,
  "Categoria": "Ideas",
  "Estado": ["Exclusive", "Last Chance"],
  "Altura": "32cm",
  "Ancho": "25cm",
  "Profundidad": "17cm",
  "Modelo": 10323,
  "Piezas": 2651,
  "Edad minima": 18,
  "Anio Lanzamiento": 2018,
  "Descripcion": "Take a trip back to the 1980s with this LEGO® Icons PAC-MAN Arcade (10323) building set for adults. Enjoy a rewarding project recreating the iconic maze-chase cabinet arcade game, considered by many as the most influential video game of all time.",
  "Calificacion": "4.8",
  "Cantidad": 3,
  "Img": ["https:\/\/jaysbrickblog.com\/wp-content\/uploads\/2023\/05\/10323-PAC-MAN-Arcade-Machine-Arcade-Machine-1892x2048.jpg", "https:\/\/www.toysnbricks.com\/wp-content\/uploads\/2023\/05\/18-LEGO-Icons-10323-PAC-MAN-Arcade-June-2023-Release-Date-Back-Box.jpg"]
 },
 {
  "Id": 28,
  "Nombre": "Atari 2600",
  "Precio": 369.99,
  "Categoria": "Ideas",
  "Estado": ["Hard to Find"],
  "Altura": "8cm",
  "Ancho": "33cm",
  "Profundidad": "22cm",
  "Modelo": 10306,
  "Piezas": 2532,
  "Edad minima": 18,
  "Anio Lanzamiento": 2019,
  "Descripcion": "Take a trip back to the 1980s with this LEGO® Atari® 2600 (10306) building set for adults. Enjoy a rewarding project creating all the details of this replica console, game cartridges and joystick. Gaming fans will love the 3 mini builds depicting themes from 3 popular Atari® games. There’s even a hidden 1980s scene to build for total nostalgia overload.",
  "Calificacion": "4.7",
  "Cantidad": 5,
  "Img": ["https:\/\/i.pinimg.com\/736x\/06\/f3\/88\/06f388640f6b251fd488707ecef6ef4a.jpg", "https:\/\/s3-us-west-2.amazonaws.com\/media.brothers-brick.com\/2022\/07\/LEGO-Icons-10306-Atari-2600-HKFM4-36.jpg"]
 },
 {
  "Id": 29,
  "Nombre": "The Globe",
  "Precio": 339.99,
  "Categoria": "Ideas",
  "Estado": ["Hard to Find", "Last Chance", "New"],
  "Altura": "40cm",
  "Ancho": "30cm",
  "Profundidad": "26cm",
  "Modelo": 21332,
  "Piezas": 2585,
  "Edad minima": 18,
  "Anio Lanzamiento": 2024,
  "Descripcion": "Where do you want to go today? Dream of your next travel destination as you build The Globe (21332). Created by a fan-designer and brought to the world by the LEGO® Ideas team, this display model recreates the spinning movement of a vintage Earth globe with the help of LEGO Technic™ elements and features glow-in-the-dark tiles decorated with the names of continents and oceans. There are buildable ship and compass icons, plus ‘The Earth’ nameplate to complete a charming centrepiece to enhance the decor of any home or office.",
  "Calificacion": "4.5",
  "Cantidad": 2,
  "Img": ["https:\/\/hips.hearstapps.com\/vader-prod.s3.amazonaws.com\/1643236922-lego-ideas-globe-box-1643134200.jpg?crop=1xw:1xh;center,top&resize=980:*", "https:\/\/mlpnk72yciwc.i.optimole.com\/cqhiHLc.IIZS~2ef73\/w:auto\/h:auto\/q:75\/https:\/\/bleedingcool.com\/wp-content\/uploads\/2022\/01\/Screen-Shot-2022-01-20-at-10.47.07-AM.jpg"]
 },
 {
  "Id": 30,
  "Nombre": "Polaroid OneStep Camera",
  "Precio": 89.99,
  "Categoria": "Ideas",
  "Estado": ["Last Chance"],
  "Altura": "9cm",
  "Ancho": "9cm",
  "Profundidad": "15cm",
  "Modelo": 21345,
  "Piezas": 516,
  "Edad minima": 18,
  "Anio Lanzamiento": 2017,
  "Descripcion": "Enjoy quality time capturing iconic details such as the viewfinder, Color Spectrum and exposure compensation dial, and add stickers with authentic graphics. Build a Polaroid Time-Zero Supercolor SX-70 Land Film pack containing 3 illustrated ‘photos’, including one of Polaroid inventor Edwin H. Land. Choose a photo, load it into the camera, press the red shutter button and the photo is ejected, just like the real thing.",
  "Calificacion": "4.7",
  "Cantidad": 3,
  "Img": ["https:\/\/goodshomedesign.com\/wp-content\/uploads\/2023\/12\/lego-polaroid-camera-set5.jpeg", "https:\/\/www.thebrickfan.com\/wp-content\/uploads\/2023\/12\/LEGO-Ideas-Polaroid-OneStep-SX-70-Camera-21345-2.jpg"]
 },
 {
  "Id": 31,
  "Nombre": "Typewriter",
  "Precio": 359.99,
  "Categoria": "Ideas",
  "Estado": ["Hard to Find", "Last Chance"],
  "Altura": "11cm",
  "Ancho": "27cm",
  "Profundidad": "26cm",
  "Modelo": 21327,
  "Piezas": 2079,
  "Edad minima": 18,
  "Anio Lanzamiento": 2021,
  "Descripcion": "Unplug from your digital life and recall simpler times as you build a LEGO® Ideas model of an old-fashioned typewriter (21327). The design is inspired by the classic typewriter used by the LEGO Group’s founder Ole Kirk Kristiansen, and it moves and sounds just like the real thing. The brick-built centre typebar rises each time a letter key is pressed and is linked to the carriage that moves across as you type. There is also a platen roller that you can feed real paper into.",
  "Calificacion": "4.5",
  "Cantidad": 2,
  "Img": ["https:\/\/i.kinja-img.com\/image\/upload\/c_fit,q_60,w_645\/5db30dc2585386533a665f759f6eda6b.jpg", "https:\/\/truenorthbricks.com\/wp-content\/uploads\/2021\/06\/Typewriter02.jpg"]
 },
 {
  "Id": 32,
  "Nombre": "Stratocaster",
  "Precio": 179.99,
  "Categoria": "Ideas",
  "Estado": ["Hard to Find", "Last Chance"],
  "Altura": "35cm",
  "Ancho": "10cm",
  "Profundidad": "2cm",
  "Modelo": 21329,
  "Piezas": 1074,
  "Edad minima": 18,
  "Anio Lanzamiento": 2022,
  "Descripcion": "Create your own brick-built 1970s Fender® Stratocaster™ guitar and 65 Princeton® Reverb amplifier with this LEGO® Ideas set (21329). Recall the legendary musicians who have played a Stratocaster® as you recreate its iconic curves and add authentic details such as the posable whammy bar, pickup switch and tuning pegs. The buildable amp has removable panels for easy viewing of the motherboard, reverb tank, speaker and other interior details, plus rubber cables to connect it to the guitar and footswitch.",
  "Calificacion": "4.4",
  "Cantidad": 2,
  "Img": ["https:\/\/www.lowyat.net\/wp-content\/uploads\/2021\/09\/LEGO-Ideas-Fender-Stratocaster-21329-3.jpg", "https:\/\/mlpnk72yciwc.i.optimole.com\/cqhiHLc.IIZS~2ef73\/w:auto\/h:auto\/q:75\/https:\/\/bleedingcool.com\/wp-content\/uploads\/2021\/09\/Screen-Shot-2021-09-16-at-8.41.10-AM.jpg"]
 },
 {
  "Id": 33,
  "Nombre": "Grand Piano",
  "Precio": 599.99,
  "Categoria": "Ideas",
  "Estado": ["Hard to Find"],
  "Altura": "23cm",
  "Ancho": "31cm",
  "Profundidad": "36cm",
  "Modelo": 21323,
  "Piezas": 3662,
  "Edad minima": 18,
  "Anio Lanzamiento": 2017,
  "Descripcion": "Feel the pride of building a sophisticated, brick-built version of a concert grand piano that you can actually play music with! Recreate the hammer action of each piano key, the moving pedal and authentic details such as the propped-open top lid and fallboard. Turn on the motor and then you are all set to play wonderful music – select user play on the free LEGO Powered Up app to play the notes yourself or activate auto play and just listen.",
  "Calificacion": "4.4",
  "Cantidad": 5,
  "Img": ["https:\/\/s3-us-west-2.amazonaws.com\/media.brothers-brick.com\/2020\/07\/LEGO-Ideas-21323-Grand-Piano-5XVCG-13-624x632.jpg", "https:\/\/s3-us-west-2.amazonaws.com\/media.brothers-brick.com\/2020\/07\/LEGO-Ideas-21323-Grand-Piano-5XVCG-10-624x774.jpg"]
 },
 {
  "Id": 34,
  "Nombre": "The Insect Collection",
  "Precio": 124.99,
  "Categoria": "Ideas",
  "Estado": ["Exclusive", "Last Chance"],
  "Altura": "18cm",
  "Ancho": "17cm",
  "Profundidad": "16cm",
  "Modelo": 21342,
  "Piezas": 1111,
  "Edad minima": 18,
  "Anio Lanzamiento": 2015,
  "Descripcion": "Display spectacular insects from around the world in your home with the LEGO® Ideas The Insect Collection (21342). A charming gift for nature lovers, this set features detailed, life-size, buildable models of a blue morpho butterfly, a Hercules beetle and a Chinese mantis in their natural habitats. These beautiful models can be displayed separately or together as a stunning piece of nature décor.",
  "Calificacion": "4.9",
  "Cantidad": 3,
  "Img": ["https:\/\/i.ebayimg.com\/images\/g\/jJIAAOSwCI9lYhQE\/s-l1600.jpg", "https:\/\/jaysbrickblog.com\/wp-content\/uploads\/2023\/08\/21342-LEGO-Insect-Collection-Box-back-2048x1639.jpg"]
 },
 {
  "Id": 35,
  "Nombre": "The Starry Night",
  "Precio": 259.99,
  "Categoria": "Ideas",
  "Estado": ["Hard to Find", "Last Chance"],
  "Altura": "30cm",
  "Ancho": "38cm",
  "Profundidad": "12cm",
  "Modelo": 21333,
  "Piezas": 2316,
  "Edad minima": 18,
  "Anio Lanzamiento": 2019,
  "Descripcion": "Build creativity. Build concentration. Build your own 3D LEGO® brick version of one of Vincent van Gogh’s most celebrated artworks, The Starry Night, which can be seen at The Museum of Modern Art (MoMA) in New York City. Discover innovative building techniques to capture Van Gogh’s swirling brushstrokes, and hang your completed masterpiece by the hook on a wall or display it freestanding. This wonderfully detailed LEGO Ideas model (21333) comes with an adjustable display arm on which the Vincent van Gogh minifigure can stand with his paintbrush, palette and easel.",
  "Calificacion": "4.8",
  "Cantidad": 2,
  "Img": ["https:\/\/designyoutrust.com\/wp-content\/uploads\/2022\/06\/1-1.jpg", "https:\/\/cdn11.bigcommerce.com\/s-g8qyo70dwl\/images\/stencil\/1920w\/products\/4140\/8239\/8575b38e157798%20b__56328.1691182029.jpg?c=1"]
 },
 {
  "Id": 36,
  "Nombre": "Land Rover Defender 90",
  "Precio": 369.99,
  "Categoria": "Ideas",
  "Estado": ["Hard to Find", "Last Chance", "New"],
  "Altura": "16cm",
  "Ancho": "16cm",
  "Profundidad": "32cm",
  "Modelo": 10317,
  "Piezas": 2336,
  "Edad minima": 18,
  "Anio Lanzamiento": 2023,
  "Descripcion": "Staying true to the original 1984 model, this car collectible is sand green with a white roof, black wheel trims and a brown interior. It features functional steering, working suspension and a choice of 2 engines. Car-lovers can keep the basic vehicle as a Land Rover Estate or customise it for an epic off-road adventure using accessories such as a roll cage, fire extinguisher, roof rack, an engine snorkel and traction boards for crossing muddy terrain.",
  "Calificacion": "4.5",
  "Cantidad": 2,
  "Img": ["https:\/\/www.acquiremag.com\/.image\/c_limit%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_860\/MTk2NTgwMDU4NTUzMzk1MDA2\/lego-defender-90-2.jpg", "https:\/\/werd.com\/wp-content\/uploads\/2023\/03\/lego-Land-Rover-Classic-Defender-90-2.jpg"]
 }
]
